alias bm='python3 main.py benchmark'
alias init='python3 main.py init'
alias run='python3 main.py run'
alias plot='python3 main.py plot'
alias compare='python3 main.py compare'
alias meshgen='python3 main.py meshgen'
alias bmove='python3 main.py move'